### ISSUE TITLE
Question: Does this also automatically install the Jupytext Labextension?

### ISSUE THREAD

**Issue by krinsman** [conda-forge/jupytext-feedstock#28]
After installing this conda package, JupyterLab needed to rebuild to accommodate the newly installed Jupytext LabExtension. However, I don't recall running `jupyter labextension install jupytext` myself. I also can't find where that or an equivalent command is included in this recipe.

Does this recipe install the LabExtension automatically? 
Or does perhaps the `setup.py` of the PyPI package that this conda package is based on?

I am curious because I am interested in workflows that install server extensions and lab extensions simultaneously and automatically.

**Comment by mwouts** [comment]
Hello @krinsman , indeed the lab extension (and the server extension, and the notebook extension) are installed and activated by `setup.py`. The corresponding lines are here:

https://github.com/mwouts/jupytext/blob/master/setup.py#L27-L35

**Comment by krinsman** [comment]
Awesome, thanks so much!

**Comment by mwouts** [comment]
I'm glad it helped! And thanks for the linked issue. I agree with your point, it's so helpful for the end user when everything is installed automatically.

Two other packages in which I search some inspiration for this are [plotly.py](https://github.com/plotly/plotly.py/blob/master/packages/python/plotly/setup.py) and [voila](https://github.com/voila-dashboards/voila/blob/master/setup.py). They both include a `NPM` class which I'd be curious to know more about. Is it related to the fact that we don't even have to _recompile_ JupyterLab when we install Plotly? Unless Plotly/Voila in JupyterLab use something else than an extension?

**Comment by krinsman** [comment]
I'm not sure -- I vaguely remember having to manually install the JupyterLab plotly extension after installing the conda plotly package (I think it was conda-forge), so it seems to me like Jupytext's solution works better than plotly's. (Have no idea about Voila)

Does the solution in the jupytext `setup.py` also work when the user's Python/Jupyter are installed somewhere else besides a conda environment?

Personally I would have no problem with that if that were the case, since I always running Jupyter from within a conda environment. I guess I could imagine other people complaining about it though.

**Comment by krinsman** [comment]
@mwouts Did you ever get a `webpackMissingModule` error when setting this up initially? If so, what turned out to be the solution?

I used `npm pack` to create a tarball version of the lab extension, edited the `setup.py` to mirror what is done in `jupytext`. Everything seemed to work, JupyterLab discovered the extension and requested a rebuild. But after building, the extension did not show up (even though the output of `jupyter labextension list` would suggest that everything is fine), and the browser's Javascript console reported the above error from webpack.

<img width="834" alt="Captura de Pantalla 2019-11-27 a la(s) 1 35 26 p  m" src="https://user-images.githubusercontent.com/31422259/69761091-2de51b00-111b-11ea-9de3-3ef95d6225cb.png">

This is probably something which it isn't possible for you to help with since it's probably too specific to the setup of this project, but it seemed to make sense to ask anyway in case it turned out to be a generally applicable problem which you also ran into.

**Comment by mwouts** [comment]
Well, all that I know about JupyterLab extension is summarized in that [README.md](https://github.com/mwouts/jupytext/blob/master/packages/labextension/README.md)... but it turns out that I am also interested in `slurm`. Is that https://github.com/NERSC/jupyterlab-slurm which you are trying to package?

**Comment by krinsman** [comment]
Yes, exactly, I am one of the maintainers for Jupyterlab-Slurm. The idea was to reduce the number of install steps, since it consists of both a notebook server extension and a JupyterLab extension.
