### ISSUE TITLE
Is the conda package for Jupytext 1.9.0 correct?

### ISSUE THREAD

**Issue by mwouts** [conda-forge/jupytext-feedstock#53]
There are two builds already for Jupytext 1.9.0, but I'm not so sure they are correct, because
- the first one was created by a branch created on the `jupytext-feedstock` project (I saw too late that it should have been created on a fork)
- and I can't install them, at least not with `conda install jupytext==1.9.0 -c conda-forge`, which ends with this error:
```
PackagesNotFoundError: The following packages are not available from current channels:

  - jupytext==1.9.0
```

@grst, would you mind to have a look at these builds? Do you see how we could fix them? Many thanks!

**Comment by martinRenou** [comment]
It always takes a bit of time between merging PRs in the feedstock and actually having the package available on conda-forge. Maybe it's available now?

**Comment by martinRenou** [comment]
It is available now, but it looks like the labextension is not there. Looking at the logs it looks like the build failed silently: https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=258738&view=logs&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=e5c8ab1d-8ff9-5cae-b332-e15ae582ed2d&l=542. I'll investigate.

**Comment by martinRenou** [comment]
Looks like the labextension is not in the `sdist`. You'll need to make a patch release, I am pushing a PR fixing this.

**Comment by martinRenou** [comment]
https://github.com/mwouts/jupytext/pull/703

**Comment by martinRenou** [comment]
It might be worth adding a test in the feedstock checking that the labextension is correctly installed, see https://github.com/conda-forge/ipycanvas-feedstock/blob/master/recipe/meta.yaml#L41

**Comment by mwouts** [comment]
Yes, thank you @martinRenou . I'll see how to add this test.

Also I changed `host` to `build` in the `meta.yaml`, but maybe I shouldn't have, at least `jupyterlab-feedstock` also uses `host`:

https://github.com/conda-forge/jupyterlab-feedstock/blob/b4c7253b2ad0a0a96d700521912edea4b890280e/recipe/meta.yaml#L23-L31

**Comment by grst** [comment]
afaik `noarch` packages should only have `host`. `build` is only for native compilation. 
In practice, both should produce a working package. 

Have you already figured out the remaining issues or do I still need to look at something?

**Comment by mwouts** [comment]
> afaik noarch packages should only have host. build is only for native compilation.

Thank you @grst ! I think it should be OK with the next version (and this morning I am able indeed to install `jupytext=1.9.0` from conda-forge, maybe I did not left it enough time yesterday). I plan to make the following changes:
- change `build` back to `host`
- add a test in the feedstock to make sure that the labextension is installed, as suggested by @martinRenou above

**Comment by mwouts** [comment]
I confirm that I was able to install `jupytext=1.9.1` with
```
conda create -n test jupyterlab=3 jupytext -c conda-forge
```
and then, I could start Jupyter Lab 3.0 - and the Jupytext extension was working fine.
